apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ado-agents
resources:
  - ../../../base
patches:
  - target:
      kind: Deployment
      name: ado-agent-std
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "CHANGE_ME_DEV_ACR.azurecr.io/ado/agent:1.0.0"
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "pool-eus-std"
  - target:
      kind: Deployment
      name: ado-agent-heavy
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "CHANGE_ME_DEV_ACR.azurecr.io/ado/agent:1.0.0"
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "pool-eus-heavy"
  - target:
      kind: ScaledObject
      name: ado-agent-std
    patch: |
      - op: replace
        path: /spec/triggers/0/metadata/poolID
        value: "12345"
  - target:
      kind: ScaledObject
      name: ado-agent-heavy
    patch: |
      - op: replace
        path: /spec/triggers/0/metadata/poolID
        value: "67890"
